apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels: { app: hello-world }
spec:
  selector: { app: hello-world }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: ClusterIP
