apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: platform-demo
  app.kubernetes.io/managed-by: argocd

images:
  - name: registry.onstackit.cloud/HARBOR_PROJECT/platform-demo
    newTag: latest
