apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: test-webinar
  app.kubernetes.io/managed-by: argocd

images:
  - name: registry.onstackit.cloud/registry/test-webinar
    newTag: latest
