apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: NAMESPACE_NAME

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: platform-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.onstackit.cloud/HARBOR_PROJECT/platform-demo:TAG
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: prod
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
